//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moms_food.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews_response
    {
        public int ID { get; set; }
        public int ReviewsID { get; set; }
        public int UserID { get; set; }
        public string Description { get; set; }
        public string Photos { get; set; }
        public Nullable<double> note { get; set; }
    
        public virtual Reviews Reviews { get; set; }
        public virtual User User { get; set; }
    }
}
